language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master
    - ng6-revamp

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod --project carousel
  - ng build --prod
